package com.henu.exam.dao;

import com.henu.exam.bean.QuestionInfo;
import com.henu.exam.bean.QuestionInfoKey;

public interface QuestionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_db_info
     *
     * @mbg.generated Mon Aug 12 14:23:48 CST 2019
     */
    int deleteByPrimaryKey(QuestionInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_db_info
     *
     * @mbg.generated Mon Aug 12 14:23:48 CST 2019
     */
    int insert(QuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_db_info
     *
     * @mbg.generated Mon Aug 12 14:23:48 CST 2019
     */
    int insertSelective(QuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_db_info
     *
     * @mbg.generated Mon Aug 12 14:23:48 CST 2019
     */
    QuestionInfo selectByPrimaryKey(QuestionInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_db_info
     *
     * @mbg.generated Mon Aug 12 14:23:48 CST 2019
     */
    int updateByPrimaryKeySelective(QuestionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_db_info
     *
     * @mbg.generated Mon Aug 12 14:23:48 CST 2019
     */
    int updateByPrimaryKey(QuestionInfo record);
}