spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: exam
    password: UpC8HnS3MUjC9G3
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 5
      max-active: 50

      timeBetweenEvictionRunsMillis: 20000
      minEvictableIdleTimeMillis: 3600000
      removeAbandoned: true
      removeAbandonedTimeout: 40

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

#  redis:
#    host: 127.0.0.1
#    port: 6379


#mybatis:
#  mapper-locations: classpath*:/mapper/*Dao.xml
#  type-aliases-package: com.springboot.disk.dao